#端口
server:
  port: 9001

#eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#服务名
spring:
  application:
    name: video-server
  zipkin:
    base-url: http://47.94.9.39:9411/



